bases:
    - ../base

namespace: sallahli
resources:
    - namespace.yaml
    - ingress.yaml
    - postgres-sallahli.yaml
    - pvc-sallahli.yaml
    - regcred.yaml


patchesStrategicMerge:
    - sallahli-backend.yaml
